### ISSUE TITLE
IP Gateway Connection issue since updated to 7.3.0

### ISSUE THREAD

**Issue by KardelSniper** [FlyingDiver/Indigo-radiora2#43]
Hi there,
So I've been using this great plugin with my Homeworks QS system for quite some time, always worked great. But now ever since I updated to 7.3.0, the plugin just randomly ran into an issue almost everyday: it won't be able to control any devices. Log looks like this:

```
Lutron RRA2/Caséta Debug       Family Room Shade 3: actionControlDimmerRelay sending: '#OUTPUT,126,1,0' to gateway 1331183014
Lutron RRA2/Caséta Debug       Lutron IP Gateway: Sending command: '#OUTPUT,126,1,0'
Lutron RRA2/Caséta Warning     Lutron IP Gateway: Error sending IP command, resetting connection:  'int' object has no attribute 'sendall'
```
Every time I reload the plugin it's back to normal. Then the issue repeats after some hours. Just wondering if this is a bug or did I do the upgrade wrongly? Thank you :)

**Comment by FlyingDiver** [comment]
What version did you upgrade from?

The IP gateway appears to be working properly.  But for some reason the connection to the HW system seems to get lost.

**Comment by FlyingDiver** [comment]
Also, look in the log for the previous command sent to Homeworks, even if it worked.

**Comment by KardelSniper** [comment]
> What version did you upgrade from?
> 
> The IP gateway appears to be working properly. But for some reason the connection to the HW system seems to get lost.

I think I updated from 7.2.8. The previous commands I sent were just open/close and status requests. When it's working, it's something like this (I'll paste the log of the previous commands when this issue happens again):
```
   Lutron RRA2/Caséta Debug       Family Room Shade 2: actionControlDimmerRelay sending: '#OUTPUT,124,1,100' to gateway 1331183014
   Lutron RRA2/Caséta Debug       Lutron IP Gateway: Sending command: '#OUTPUT,124,1,100'
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: 50 characters read:
QNET> ~SHADEGRP,123,1,100.00
~SHADEGRP,123,32,0,1
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: self.buffer = 'QNET> ~SHADEGRP,123,1,100.00
~SHADEGRP,123,32,0,1'
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: msg = 'QNET> ~SHADEGRP,123,1,100.00
'
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: self.buffer = '~SHADEGRP,123,32,0,1'
   Lutron RRA2/Caséta Threaddebug Received command: QNET> ~SHADEGRP,123,1,100.00 from Gateway 1331183014
   Lutron RRA2/Caséta Debug       Gateway 1331183014 Unrecognized command: QNET> ~SHADEGRP,123,1,100.00
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: 50 characters read:
3094
~OUTPUT,124,1,100.00
~OUTPUT,124,29,6
~OUT
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: self.buffer = '~SHADEGRP,123,32,0,13094
~OUTPUT,124,1,100.00
~OUTPUT,124,29,6
~OUT'
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: msg = '~SHADEGRP,123,32,0,13094
'
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: self.buffer = '~OUTPUT,124,1,100.00
~OUTPUT,124,29,6
~OUT'
   Lutron RRA2/Caséta Threaddebug Received command: ~SHADEGRP,123,32,0,13094 from Gateway 1331183014
   Lutron RRA2/Caséta Debug       Gateway 1331183014 Unrecognized command: ~SHADEGRP,123,32,0,13094
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: 45 characters read:
PUT,124,30,1,100.00
~OUTPUT,124,32,0,13094

   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: self.buffer = '~OUTPUT,124,1,100.00
~OUTPUT,124,29,6
~OUTPUT,124,30,1,100.00
~OUTPUT,124,32,0,13094
'
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: msg = '~OUTPUT,124,1,100.00
'
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: self.buffer = '~OUTPUT,124,29,6
~OUTPUT,124,30,1,100.00
~OUTPUT,124,32,0,13094
'
   Lutron RRA2/Caséta Threaddebug Received command: ~OUTPUT,124,1,100.00 from Gateway 1331183014
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,124,1,100.00
   Lutron RRA2/Caséta Debug       Received: Shade Family Room Shade 2 opening set to 100.0
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: self.buffer = '~OUTPUT,124,29,6
~OUTPUT,124,30,1,100.00
~OUTPUT,124,32,0,13094
'
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: msg = '~OUTPUT,124,29,6
'
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: self.buffer = '~OUTPUT,124,30,1,100.00
~OUTPUT,124,32,0,13094
'
   Lutron RRA2/Caséta Threaddebug Received command: ~OUTPUT,124,29,6 from Gateway 1331183014
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,124,29,6
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: self.buffer = '~OUTPUT,124,30,1,100.00
~OUTPUT,124,32,0,13094
'
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: msg = '~OUTPUT,124,30,1,100.00
'
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: self.buffer = '~OUTPUT,124,32,0,13094
'
   Lutron RRA2/Caséta Threaddebug Received command: ~OUTPUT,124,30,1,100.00 from Gateway 1331183014
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,124,30,1,100.00
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: self.buffer = '~OUTPUT,124,32,0,13094
'
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: msg = '~OUTPUT,124,32,0,13094
'
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: self.buffer = ''
   Lutron RRA2/Caséta Threaddebug Received command: ~OUTPUT,124,32,0,13094 from Gateway 1331183014
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,124,32,0,13094
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: 50 characters read:
~SHADEGRP,123,32,2,100.00
~OUTPUT,124,32,2,100.00
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: self.buffer = '~SHADEGRP,123,32,2,100.00
~OUTPUT,124,32,2,100.00'
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: msg = '~SHADEGRP,123,32,2,100.00
'
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: self.buffer = '~OUTPUT,124,32,2,100.00'
   Lutron RRA2/Caséta Threaddebug Received command: ~SHADEGRP,123,32,2,100.00 from Gateway 1331183014
   Lutron RRA2/Caséta Debug       Gateway 1331183014 Unrecognized command: ~SHADEGRP,123,32,2,100.00
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: 2 characters read:


   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: self.buffer = '~OUTPUT,124,32,2,100.00
'
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: msg = '~OUTPUT,124,32,2,100.00
'
   Lutron RRA2/Caséta Threaddebug Lutron IP Gateway: self.buffer = ''
   Lutron RRA2/Caséta Threaddebug Received command: ~OUTPUT,124,32,2,100.00 from Gateway 1331183014
   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,124,32,2,100.00
```

**Comment by FlyingDiver** [comment]
SHADEGRP is new.  I think it must be HW specific.  If you want support for that command, create a new issue.

Otherwise, I'm hoping that there's some clue in the log prior to the failure (next time).

**Comment by KardelSniper** [comment]
Thank you very much! Oh yeah as you pointed out I just noticed that SHADEGRP is not recognized; because it has been working so I just supposed this is no difference than regular on/off devices or dimmers. Let me try to open another issue.

Today so far the bug hasn't happened yet. I'll report back once it's happening again :)

**Comment by FlyingDiver** [comment]
I think SHADEGRP is new.  I'll have to get into the current RRa2 software and see if it's in there.  Might be Homeworks specific.

**Comment by KardelSniper** [comment]
I created a new issue for this. Found this command in the 2019-11 integration protocol. I agree it should be pretty new, but I think RRa2 also has support for shades, so I doubt it's Homeworks specific. Seems this can set shade location.

Thank you!

**Comment by FlyingDiver** [comment]
Non repeatable?

**Comment by KardelSniper** [comment]
Seems like it's kind of linked to network issues. I observed every time there is a cut in the network indigo is connected to (like restarting router, changing IP etc), this tends to happen. If I can be certain of its pattern I'll report it back here. Thank you!
